"""Type stubs for mutagen_rs."""

from typing import Any, Optional, Sequence, overload

__version__: str
version: tuple[int, ...]
version_string: str

class Encoding(int):
    LATIN1: Encoding
    UTF16: Encoding
    UTF16BE: Encoding
    UTF8: Encoding

class PaddingInfo:
    padding: int
    size: int
    def __init__(self, padding: int = -1, size: int = 0) -> None: ...

class _InfoProxy:
    length: float
    channels: int
    sample_rate: int
    bitrate: int
    bits_per_sample: Optional[int]
    version: Optional[float]
    layer: Optional[int]
    mode: Optional[int]
    protected: Optional[bool]
    bitrate_mode: Optional[int]
    total_samples: Optional[int]
    codec: Optional[str]
    def pprint(self) -> str: ...

class _CachedFile(dict[str, Any]):
    info: _InfoProxy
    filename: str
    @property
    def tags(self) -> Optional[dict[str, Any]]: ...
    @property
    def pictures(self) -> list[dict[str, Any]]: ...
    def save(self, *args: Any, **kwargs: Any) -> None: ...
    def delete(self) -> None: ...
    def add_tags(self) -> None: ...
    def clear(self) -> None: ...
    def pprint(self) -> str: ...
    def keys(self) -> list[str]: ...

class _MP3File(_CachedFile): ...
class _FLACFile(_CachedFile): ...
class _OggVorbisFile(_CachedFile): ...
class _MP4File(_CachedFile): ...

FileType = _CachedFile

class _ID3Value(list[str]):
    encoding: Encoding
    @property
    def text(self) -> '_ID3Value': ...
    def _pprint(self) -> str: ...

class _EasyTagView(dict[str, list[str]]):
    def save(self, *args: Any, **kwargs: Any) -> None: ...

class EasyID3(_EasyTagView):
    filename: Optional[str]
    @property
    def info(self) -> Optional[_InfoProxy]: ...
    @property
    def tags(self) -> 'EasyID3': ...
    def __init__(self, filename: Optional[str] = None) -> None: ...

class EasyMP4Tags(_EasyTagView):
    filename: Optional[str]
    @property
    def info(self) -> Optional[_InfoProxy]: ...
    @property
    def tags(self) -> 'EasyMP4Tags': ...
    def __init__(self, filename: Optional[str] = None) -> None: ...

class EasyMP3(_MP3File):
    @property
    def tags(self) -> EasyID3: ...
    def keys(self) -> list[str]: ...

class EasyMP4(_MP4File):
    @property
    def tags(self) -> EasyMP4Tags: ...
    def keys(self) -> list[str]: ...

def MP3(filename: str) -> _MP3File: ...
def FLAC(filename: str) -> _FLACFile: ...
def OggVorbis(filename: str) -> _OggVorbisFile: ...
def MP4(filename: str) -> _MP4File: ...
def File(filename: str, easy: bool = False) -> Optional[_CachedFile]: ...
def batch_open(filenames: list[str]) -> dict[str, dict[str, Any]]: ...
def clear_cache() -> None: ...
def clear_all_caches() -> None: ...
def _fast_read(filename: str) -> dict[str, Any]: ...
def _fast_info(filename: str) -> dict[str, Any]: ...
def _fast_read_seq(filenames: list[str]) -> list[dict[str, Any]]: ...
def _fast_batch_read(filenames: list[str]) -> dict[str, dict[str, Any]]: ...

# Re-exported from Rust
class MPEGInfo: ...
class StreamInfo: ...
class OggVorbisInfo: ...
class MP4Info: ...
class ID3: ...
class VComment: ...
class MP4Tags: ...
class BatchResult: ...
def batch_diag(filenames: list[str]) -> dict[str, Any]: ...

# Errors
class MutagenError(Exception): ...
class ID3Error(MutagenError): ...
class ID3NoHeaderError(ID3Error): ...
class MP3Error(MutagenError): ...
class HeaderNotFoundError(MP3Error): ...
class FLACError(MutagenError): ...
class FLACNoHeaderError(FLACError): ...
class OggError(MutagenError): ...
class MP4Error(MutagenError): ...

Tags = dict
Metadata = dict
